### ISSUE TITLE
Controls update in PodController

### ISSUE THREAD

**Issue by MoireMotion** [MrBlueXav/Dryftor#1]
UpdateAnalogControls and DebounceControls have been updated to ProcessAnalogControls and ProcessDigitalControls

Or can use ProcessAllControls

https://github.com/electro-smith/libDaisy/commit/9245d23d676d9729ca992cf492153c1b2699d66f#diff-920f492034d2bc6fe227871a40f95a82c4a47534cf2ba419b4f1b777e9278e28

**Comment by MrBlueXav** [comment]
Fixed !
